// AUTO-GENERATED by scripts/gen-sitemap-lastmod.mjs — do not edit by hand.
// Per-route last-modified dates (W3C YYYY-MM-DD) from each page's last git
// commit, so the sitemap lastmod is stable across deploys and only moves when a
// route's content actually changes (vs. a build-time new Date() on every URL).
// Regenerate after content changes:  node scripts/gen-sitemap-lastmod.mjs
//
// Caveat: reflects each page file's OWN commits. If you change a route's
// rendered content only through a shared lib module (faq.ts, pricing.ts,
// routes-seo.ts, services.ts) without editing its page.tsx, bump that route
// here by hand (or touch the page file) before regenerating.
export const ROUTE_LASTMOD: Record<string, string> = {
  "/": "2026-08-05",
  "/apc-coagulacion-plasma-argon-merida": "2026-08-05",
  "/capsula-endoscopica-merida": "2026-08-05",
  "/cierre-fistulas-clips-endoscopicos-merida": "2026-08-05",
  "/colonoscopia-merida": "2026-08-05",
  "/consultas-digestivas-merida": "2026-08-05",
  "/contacto": "2026-08-05",
  "/cpre-merida": "2026-08-05",
  "/cpre-playa-del-carmen": "2026-07-02",
  "/dilatacion-biliar-merida": "2026-08-05",
  "/dilatacion-colonica-merida": "2026-07-02",
  "/dilatacion-esofagica-merida": "2026-07-02",
  "/diseccion-endoscopica-submucosa-esd-merida": "2026-08-05",
  "/dr-omar-quiroz": "2026-08-05",
  "/emergencias-digestivas-merida": "2026-07-21",
  "/endoprotesis-biliares-merida": "2026-08-05",
  "/endoprotesis-colonicas-merida": "2026-07-02",
  "/endoprotesis-duodenales-merida": "2026-08-05",
  "/endoprotesis-esofagicas-merida": "2026-08-05",
  "/endoscopia-merida": "2026-08-05",
  "/esclerosis-varices-gastricas-merida": "2026-08-05",
  "/extraccion-cuerpos-extranos-endoscopia-merida": "2026-08-05",
  "/gastrostomia-endoscopica-peg-merida": "2026-07-02",
  "/ligadura-hemorroides-internas-merida": "2026-07-21",
  "/ligadura-varices-esofagicas-merida": "2026-08-05",
  "/precios": "2026-08-05",
  "/reseccion-endoscopica-mucosa-emr-merida": "2026-07-02",
  "/retiro-balon-gastrico-merida": "2026-09-01",
  "/sutura-endoscopica-merida": "2026-08-05",
  "/ultrasonido-endoscopico-merida": "2026-07-02",
}
